Repository GreenpixDev/HitsAndroid, pull requests merged in 2022-05, with the labels that each got.

#82 Теперь и ссылки на гит.
  app/src/main/java/ru/hits/android/axolot/AboutUsActivity.kt
Labels: design

#83 Feature/for macros
  app/src/main/java/ru/hits/android/axolot/BlueprintActivity.kt
  app/src/main/java/ru/hits/android/axolot/blueprint/declaration/FunctionType.kt
  app/src/main/java/ru/hits/android/axolot/blueprint/declaration/MacrosBeginType.kt
  app/src/main/java/ru/hits/android/axolot/blueprint/declaration/MacrosEndType.kt
  app/src/main/java/ru/hits/android/axolot/blueprint/declaration/MacrosType.kt
  app/src/main/java/ru/hits/android/axolot/custom_spinner/UIType.kt
  app/src/main/java/ru/hits/android/axolot/view/CreatorForFunctionView.kt
  app/src/main/java/ru/hits/android/axolot/view/CreatorFunctionView.kt
  app/src/main/java/ru/hits/android/axolot/view/CreatorMacrosView.kt
  app/src/main/java/ru/hits/android/axolot/view/CreatorView.kt
  app/src/main/java/ru/hits/android/axolot/view/FunctionView.kt
  app/src/main/java/ru/hits/android/axolot/view/MacrosView.kt
  app/src/main/res/layout/creator_for_func_item.xml
  app/src/main/res/layout/creator_item.xml
  app/src/main/res/layout/param_execute_item.xml
Labels: feature

#88 ОЧ ВАЖНЫЙ ФИКС
  app/src/main/java/ru/hits/android/axolot/blueprint/project/AxolotProgram.kt
  app/src/main/java/ru/hits/android/axolot/blueprint/project/AxolotProject.kt
  app/src/main/java/ru/hits/android/axolot/blueprint/project/libs/AxolotDefaultLibrary.kt
  app/src/main/java/ru/hits/android/axolot/blueprint/project/libs/AxolotNativeLibrary.kt
  app/src/main/java/ru/hits/android/axolot/interpreter/type/primitive/BooleanType.kt
  app/src/main/java/ru/hits/android/axolot/interpreter/type/primitive/FloatType.kt
  app/src/main/java/ru/hits/android/axolot/interpreter/type/primitive/IntType.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/ru/hits/android/axolot/compiler/BlueprintCompilerTest.kt
Labels: fix

#89 ФИКС РЕГЕКСА
  app/src/main/java/ru/hits/android/axolot/blueprint/project/libs/AxolotNativeLibrary.kt
  app/src/main/java/ru/hits/android/axolot/interpreter/service/impl/executable/regex/NodeRegexFindService.kt
Labels: fix
